### PR TITLE
Add derived type structure and additional unit tests for cpld_gridgen; fix failing ocnice_prep unit test 

### LINKED ISSUE #18: increase unit-test coverage for cpld_gridgen
With the regional fix file generation capability, additional unit tests should be added to ensure that the regional grid is being created correctly from the global grid (the regional is a cut-out domain of the global).

### LINKED ISSUE #19: refactor to use derived types for multiple grid stagger locations
Currently the code has 4 arrays for each stagger location; the center lats and lons and the vertices (corner) lats and lons. Adding a derived type for the global grid and then defining a type for each stagger location can simplify the code. For example,

```
  type :: grid
    real(dbl_kind), allocatable :: lat(:,:)
    real(dbl_kind), allocatable :: lon(:,:)
    real(dbl_kind), allocatable :: latvert(:,:,:)
    real(dbl_kind), allocatable :: lonvert(:,:,:)
    real(dbl_kind), allocatable :: xlat(:)
    real(dbl_kind), allocatable :: xlon(:)
    integer,                    :: iVert(nv)
    integer                     :: jVert(nv)
  end type grid
  type(grid) :: Ct, Cu, Cv, Bu
```

### LINKED ISSUE #649: add additional unit test for cpld_gridgen for vertex retrievals
A second unit test should be added for the cpld_gridgen utility which tests the retrieval of the vertex points at each stagger location.

### LINKED ISSUE #1131: minor cleanup & warning fix for cpld_gridgen and ocnice_prep
Both of these utilities have annoying manual insertion of a directory slash (eg ``//'/'//``) when creating character strings for path and file names. These should be cleaned up for readability. 

In cpld_gridgen, there is an annoying warning that gets triggered in DEBUG mode:

```
forrtl: warning (406): fort: (1): In call to FIND_ANGQ, an array temporary was created for argument #263 
```

that should also be resolved. Note this will mean modification of the argument list for cpld_gridgen's unit test.

Since work for the AR domain (#1118) will require adding an additional unit test, I prefer to do this work first  (before opening the PR for the AR work).

### LINKED ISSUE #1134: refactor cpld_gridgen to use a derived type structure for grid variables
The cpld_gridgen utility relies of the use of global arrays defined within ``grdvars.F90`` to carry the various grid domain values through the code. This makes adding unit tests difficult (if not impossible). The various domain arrays should be placed into a derived type structure. Unit tests can then allocate small component arrays for use by the test. Also, routines (such as the netCDF write routines) can get the entire structure w/o adding excessively long argument lists.

### LINKED ISSUE #1136: ocnice_prep unit test is silently failing
Looking at the last ctest from the last commit to develop, the ocnice_prep unit test is passing for the wrong reason. The tested input nml files exist in the tests/data directory but the test is failing to find them.
```
31: Test command: /home/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/build/tests/ocnice_prep/ocnice_ftst_program_setup
31: Working Directory: /home/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/build/tests/ocnice_prep
31: Test timeout computed to be: 1500
31:  FATAL ERROR: input file tests/ocnice_prep/data/input.nml does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/invalid.model.nml does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/invalid.srcdim.nml does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/invalid.dstdim.nml does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/invalid.dst5p00.nml does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/ice.badvecpairs.csv does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/ocean.badvecpairs.csv does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/ice.badvecgrid.csv does not exist.           1
31:  FATAL ERROR: input file tests/ocnice_prep/data/ocean.badvecgrid.csv does not exist.           1
31:  SUCCESS!      9 tests out     9    were identified 
31/57 Test #31: ocnice_ftst_program_setup ...................   Passed    0.01 sec
```

The test reports success from here
https://github.com/ufs-community/UFS_UTILS/blob/8d75a95f5c30c4d3e135ef6f451120732041f422/sorc/ocnice_prep.fd/init_mod.F90#L74-L78

instead of finding the test namelists and correctly failing for the bad settings.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## DESCRIPTION OF CHANGES: 

A derived type structure is added for the grid variables in place of using these variables throughout the code from the grdvars.F90 module. This simplifies several routines and allows additional unit tests to be added cleanly. 

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [x] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Ursa, Hercules and WCOSS2).
- [x] Compile branch on Ursa using GNU. 5318be5d
- [x] Compile branch in 'Debug' mode on WCOSS2.
- [x] Compile with Doxygen on any machine with no errors. e1fc72f5
- [x] Run unit tests locally on any Tier 1 machine. e1fc72f5
- [x] Run relevant consistency tests locally on all Tier 1 machines. 7655e14

Optional test.

- [ ] Run full set of chgres_cube consistency tests on Ursa.

Describe any additional tests performed.

Compared against baseline on Ursa at 81ee6099 and all tests were B4B.

## ISSUE: 

- fixes #1134 
- fixes #1131
- fixes #649 
- fixes #1136

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
I want to get this in before finishing my work updating the RT system. Is there any testing I can help with?

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Thanks. I've been testing on Ursa for now. I made a few more changes this morning and everything on Ursa looks good. If you're able to complete the testing on the WCOSS2 and the MSU machines, that would be great.

**Comment by BrianCurtis-NOAA** [comment]
Dogwood/Hercules/Orion started.

**Comment by BrianCurtis-NOAA** [comment]
Hercules/orion look OK, WCOSS2 timed out for cpld_gridgen. Lets see if I can find out why.

**Comment by BrianCurtis-NOAA** [comment]
> Hercules/orion look OK, WCOSS2 timed out for cpld_gridgen. Lets see if I can find out why.

I made a typo in the queue for WCOSS2, rerunning.

File: tests/cpld_gridgen/ftst_fill_vertices.F90 [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+  Bu%iVert = Ct%iVert + 1; Bu%jVert = Ct%jVert + 1
+
+  ! do j = ny,1,-1
+  !    print '(i3,5f8.2)',j,(Ct%lon(i,j),i=1,nx)
+  ! end do
+  ! print *
+  ! do j = ny,1,-1
+  !    print '(i3,5f8.2)',j,(Ct%lat(i,j),i=1,nx)
+  ! end do
+  ! print *
```
Comment (BrianCurtis-NOAA) [inline tests/cpld_gridgen/ftst_fill_vertices.F90]: did you want to keep these commented out parts?

File: tests/cpld_gridgen/ftst_fill_vertices.F90 [hunk 2]
```diff
@@ -0,0 +1,269 @@
...
+  testverts(:) = (/Ct%xlat(1)+1.0e-8,Ct%xlat(i),Ct%lat(i,j),Ct%lat(1,j)/)
+  nt = nt + 1; msg = 'Bu lat vertices from Ct grid at nx,ny'
+  call assert_equal(Bu%latvert(nx,ny,:),testverts,0.0_dbl_kind,msg,status,msg_out)
+  if (.not. status) ispassing(nt) = .true.    ! failure was caught
+  testmsg(nt) = 'Expected '//trim(msg_out)
+
+  ntests = nt
+  ! do nt = 1,ntests
+  !    print '(i5,a)',nt,' '//trim(testmsg(nt))
+  ! end do
```
Comment (BrianCurtis-NOAA) [inline tests/cpld_gridgen/ftst_fill_vertices.F90]: or these?

File: tests/cpld_gridgen/ftst_reshape_staggers.F90 [hunk 3]
```diff
@@ -0,0 +1,216 @@
...
+  !    print '(i3,5f8.2)',j,(lon(i,j),i=1,nx)
+  ! end do
+  ! print *
+  ! do j = 1,ny
+  !    print '(i3,5f8.2)',j,(lat(i,j),i=1,nx)
+  ! end do
+  ! print *
+  ! do j = 1,ny
+  !    print '(i3,5i4)',j,(mask(i,j),i=1,nx)
+  ! end do
```
Comment (BrianCurtis-NOAA) [inline tests/cpld_gridgen/ftst_reshape_staggers.F90]: or these?

File: tests/cpld_gridgen/ftst_reshape_staggers.F90 [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+     if (.not. status) ispassing(nt) = .true.    ! failure was caught
+     testmsg(nt) = 'Expected '//trim(msg_out)
+
+     deallocate(cnlons, cnlats, cnmask, crlats, crlons)
+  end do
+
+  ntests = nt
+  !do nt = 1,ntests
+  !   print '(i5,a)',nt,' '//trim(testmsg(nt))
+  !end do
```
Comment (BrianCurtis-NOAA) [inline tests/cpld_gridgen/ftst_reshape_staggers.F90]: Or these?

**Comment by BrianCurtis-NOAA** [comment]
Can you bring in the recent PR updates and fix any issues?

File: tests/cpld_gridgen/ftst_fill_vertices.F90 (hunk 1 above)
Comment (DeniseWorthen) [reply tests/cpld_gridgen/ftst_fill_vertices.F90]: The commented out lines here and in the other files are useful for debugging a failed test; but they don't need to be kept. I'll remove them.

**Comment by DeniseWorthen** [comment]
I don't have any additional PR updates after 5318be5

**Comment by BrianCurtis-NOAA** [comment]
It shows your branch as 1 commit behind develop

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Thanks. I didn't notice that develop had updated. Should be OK now.

**Comment by BrianCurtis-NOAA** [comment]
Ran checks on Ursa to confirm that bringing in develop didn't muck anything up, all passed. Anything else you wanted to confirm before merging?

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I think we're good to merge, thanks. I tested multiple times during development and I don't see anything in the latest develop commit that would have touched either ocnice_prep or cpld_gridgen.

**Review by BrianCurtis-NOAA — APPROVED** [review]
