### PR TITLE
RT updates: Move to control file, run from master rt.sh for all testing, beginning of shellcheck linting

### LINKED ISSUE #1144: Consolidate machine specific RT scripts into one
What:
 * Consolidate all individual machine specific scripts into one for tests that have multiple scripts per machine.

Why:
 * All scripts have almost identical structure, so we should move them into one file where that one file can separate out what each specific file needs.

### LINKED ISSUE #1145: Run reg test system in parallel from top level
Reg tests should be run in parallel to speed up the time it takes to run the full suite during testing.

### LINKED ISSUE #1146: Control all reg testing from the top level
What:
 * To simplify the process for running regression testing system (with ambitions to run in a CI framework), we should be able to control which tests are run (especially if not all of them) from the top level and run from one location.
 * Previously to run individual testing one would need to go into each individual test and run manually after editing multiple scripts to be specific to their run structure (directories, accounts)

Why:
 * with hopes to move towards running on supported machines through CI, this will help that process.
 * simplify the process to one location for other PR authors to know what to do.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## DESCRIPTION OF CHANGES: 

RT updates:
- Move to control file, users only have to change variables in one place for testing.
- Run from master rt.sh for all testing
- Remove driver scripts per machine into one central driver script for each reg test.

### WHICH CONSISTENCY TESTS TO RUN:
- [x] chgres_cube
- [x] cpld_gridgen
- [x] global_cycle
- [x] grid_gen
- [x] ice_blend
- [x] ocnice_prep
- [x] regrid_sfc
- [x] snow2mdl
- [x] weight_gen

### TESTS CONDUCTED: 

- [x] Compile branch using Intel:
  - [x] Orion
  - [x] Ursa
  - [x] Hercules
  - [x] WCOSS2
- [x] Compile branch using GNU:
  - [x] Ursa
- [x] Compile branch in 'Debug' mode:
  - [x] WCOSS2
- [x] Compile with Doxygen with no errors.
- [x] Run unit tests on any Tier 1 machine.
- [x] Run relevant consistency tests:
  - [x] Orion
  - [x] Ursa
  - [x] Hercules
  - [x] WCOSS2

## DEPENDENCIES:

* None

## DOCUMENTATION:

- [x] Doxygen does not need updates.
- [ ] Doxygen is updated.

## LINKED ISSUES: 

* Closes #1144 
* Closes #1145 
* Closes #1146

### CODE REVIEW

File: reg_tests/detect_machine.sh
Comment (GeorgeGayno-NOAA) [inline reg_tests/detect_machine.sh:1]: There is a similar script in `./sorc` - `machine-setup.sh`. Can we combine them?

Comment (BrianCurtis-NOAA) [reply reg_tests/detect_machine.sh:1]: The detect_machine script would take over the setting of ${target} in sorc/machine-setup.sh. Specifically detect_machine.sh is maintained at the UFSWM level and shared with global workflow. So it makes some sense to try the same approach with UFS_UTILS.

The UFSWM has a separate script in their testing similar to sorc/machine-setup.sh at https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/module-setup.sh 

It might be worthwhile to share UFSWM's module-setup.sh instead of maintaining two separate versions.

What do you think?

Comment (GeorgeGayno-NOAA) [reply reg_tests/detect_machine.sh:1]: No problem sharing code. Can we link to a single file in another repo? Or do you plan to keep a local copy in UFS_UTILS?

Comment (BrianCurtis-NOAA) [reply reg_tests/detect_machine.sh:1]: lots of people maintaining UFSWM, it should reside there and we copy it. Future thinking might be some ufs-community maintained repo like "hpc-tools" where g-w ufswm ufs_utils etc can make use as a submodule?

**Comment by BrianCurtis-NOAA** [comment]
@GeorgeGayno-NOAA completely runs in ~25 minutes
```
Started on ufe03
Commit hash: ef8ea2656c70666c7b6004fdb6a10babd8c0255b

regrid_sfc consistency tests PASSED
weight_gen consistency tests PASSED
ocnice_prep consistency tests PASSED
cpld_gridgen consistency tests PASSED
chgres_cube consistency tests PASSED
grid_gen consistency tests PASSED
global_cycle consistency tests PASSED
ice_blend consistency tests PASSED
snow2mdl consistency tests PASSED
Total elapsed time: 24 minutes and 56 seconds
Finished on ursa
```

I need to test adding CHANGE_BASELINES to rt.control and change some of the calls to accept an exported env var. Then hopefully things don't fail.

**Comment by BrianCurtis-NOAA** [comment]
I've tested this on Ursa using the UPDATE_BASELINE=True and it works!

**Comment by BrianCurtis-NOAA** [comment]
@DavidHuber-NOAA @DeniseWorthen The main goal of these changes is to centralize the regression testing process to run the regression tests with one script, but still keep the option available to call each test individually (in case a developer wants this).

Please review these changes and I will run the tests after I just merged in from develop branch.

I suspect this may take a while and I appreciate your help with this.

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen @DavidHuber-NOAA I'd like to get this PR moving today if you have time to review.

**Comment by DeniseWorthen** [comment]
I'm not seeing an associated issue. What is this supposed to be fixing?

**Comment by BrianCurtis-NOAA** [comment]
> I'm not seeing an associated issue. What is this supposed to be fixing?

I've added issues, I hope this helps.

**Comment by DeniseWorthen** [comment]
This isn't working as expected for me oh hercules. Normally I have always gotten a very obvious "CPLD_GRIDGEN" directory in ``/work2`` which contains the rt_[X]. For example, ``/work2/noaa/stmp/dworthen/CPLD_GRIDGEN``. 

Now I see instead this path ``/work2/noaa/stmp/dworthen/ufs_utils/reg-tests/cpld_gridgen/rt_[X]``. Is that intentional?

**Comment by BrianCurtis-NOAA** [comment]
> This isn't working as expected for me oh hercules. Normally I have always gotten a very obvious "CPLD_GRIDGEN" directory in `/work2` which contains the rt_[X]. For example, `/work2/noaa/stmp/dworthen/CPLD_GRIDGEN`.
> 
> Now I see instead this path `/work2/noaa/stmp/dworthen/ufs_utils/reg-tests/cpld_gridgen/rt_[X]`. Is that intentional?

Yes, intentional for consistency.

**Comment by DeniseWorthen** [comment]
Thanks for adding the issues; I think all of these are basically issues w/ the chgres RTs (which I've never run), so I can't comment on whether this is PR an improvement. 

From my experience, there are not multiple places that need to be edited in the ``cpld_gridgen`` or ``ocnice_prep`` reg-tests in order to run the RTs for them. And I'm not clear why they would need to be run if, for example, a PR was made to chgres or the like since there isn't any overlap.

Still, as long as functionality remains to run only ``cpld_gridgen`` and ``ocnice_prep`` independently of any other reg-tests, I'm OK w/ this PR.

File: modulefiles/build.wcoss2.intel.lua [hunk 1]
```diff
@@ -82,4 +82,7 @@ load(pathJoin("nco", nco_ver))
 esmf_ver=os.getenv("esmf_ver") or "8.8.0"
 load(pathJoin("esmf-D", esmf_ver))
 
+nccmp_ver=os.getenv("nccmp_ver") or "1.9.0.1"
+load(pathJoin("nccmp-D", nccmp_ver))
+
```
Comment (DavidHuber-NOAA) [inline modulefiles/build.wcoss2.intel.lua:87]: Why is `nccmp` needed for building?

File: reg_tests/chgres_cube/driver.sh [hunk 2]
```diff
@@ -0,0 +1,249 @@
...
+
+    if [[ "${SCHEDULER}" == "pbs" ]]; then
+        export APRUN="mpiexec -n ${ntasks_per_node} -ppn ${ntasks_per_node} --cpu-bind core"
+        jobid=$(qsub -V -o "${logfile}" -e "${logfile}" -q "${QUEUE}" -A "${PROJECT_CODE}" -l walltime=${walltime} \
+                -N "${jobname}" -l select=${nodes}:ncpus=${ntasks_per_node}:ompthreads=${OMP_NUM_THREADS}:mem=${mem} \
+                ${dep_flag_pbs:+"${dep_flag_pbs}"} ./${script})
+        jobid=${jobid%.*}
+    elif [[ "${SCHEDULER}" == "slurm" ]]; then
+        export APRUN="srun"
+        jobid=$(sbatch --parsable --partition="${partition}" --ntasks-per-node="${ntasks_per_node}" --nodes="${nodes}" --mem="${mem}" -t "${walltime}" \
```
Comment (DavidHuber-NOAA) [inline reg_tests/chgres_cube/driver.sh:53]: Just a note that if Gaea RT support is desired at some point, this will need to include a `--clusters` option. No request for change at this time.

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good. Just a question and a comment.

File: reg_tests/chgres_cube/driver.sh (hunk 2 above)
Comment (BrianCurtis-NOAA) [reply reg_tests/chgres_cube/driver.sh:53]: OK, noted here: https://github.com/ufs-community/UFS_UTILS/issues/1138#issuecomment-4118213501

**Comment by BrianCurtis-NOAA** [comment]
> Thanks for adding the issues; I think all of these are basically issues w/ the chgres RTs (which I've never run), so I can't comment on whether this is PR an improvement.
> 
> From my experience, there are not multiple places that need to be edited in the `cpld_gridgen` or `ocnice_prep` reg-tests in order to run the RTs for them. And I'm not clear why they would need to be run if, for example, a PR was made to chgres or the like since there isn't any overlap.
> 
> Still, as long as functionality remains to run only `cpld_gridgen` and `ocnice_prep` independently of any other reg-tests, I'm OK w/ this PR.

You're correct, I made sure that each test was still able to be run without the need to call from the master script at the top level. Your RT's were the easiest to merge over to this new methodology, but probably a more drastic change in trying to stay consistent in drive location for all RT's.

**Review by DeniseWorthen — APPROVED** [review]

File: modulefiles/build.wcoss2.intel.lua (hunk 1 above)
Comment (BrianCurtis-NOAA) [reply modulefiles/build.wcoss2.intel.lua:87]: All of the driver scripts seem to do something similar to the following for wcoss2:
```
module load build.$target.$compiler
module load nccmp-D/1.9.0.1
```
so since the build doesn't need it but it won't hurt the build, and most driver scripts do this, i cheated a little and now load it in the build modulefile instead.

I couldn't think of a reason this would harm things, so please do let me know if there's something i'm missing!

Comment (DavidHuber-NOAA) [reply modulefiles/build.wcoss2.intel.lua:87]: It's probably fine. This may raise an EE2 eyebrow down the line as only required modules should be loaded at respective build/run times, but I'm fine with it for the time being.

Comment (BrianCurtis-NOAA) [reply modulefiles/build.wcoss2.intel.lua:87]: Noted! Thanks!

**Comment by BrianCurtis-NOAA** [comment]
Thanks for the reviews. I'm going to finish testing on supported machines and merge if everything goes well.

**Comment by BrianCurtis-NOAA** [comment]
All testing came out OK. Merging
