### PR TITLE
save user defined parameters in the gdas_init outputs Issue

### LINKED ISSUE #1087: save user defined parameters in the gdas_init outputs
Currently outputs of gdas_init ICs do not contain all the information to reproduce these ICs. Inclusion of such information ensures reproducibility and compatibility with different versions.

### PR DESCRIPTION
**Pull request by sanatcumar**
-This PR fixes the issue by including a text file that contains all the necessary information required for reproducibility and compatibility with different versions

## DESCRIPTION OF CHANGES: 
Additional scripting was appended to copy_coldstart_files.sh  to save all user defined parameters into a text file

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [x] Compile branch on all Tier 1 machines using Intel
  - [x] Orion
  - [x] Jet
  - [x] Ursa
  - [x] Hercules
  - [x] WCOSS2
- [x] Compile branch on Ursa using GNU.
- [x] Compile branch in 'Debug' mode on WCOSS2.
- [x] Compile with Doxygen on any machine with no errors.
- [x] Run unit tests locally on any Tier 1 machine.
- [x] Run relevant consistency tests locally on all Tier 1 machines.
  - [x] Orion
  - [x] Jet
  - [x] Ursa
  - [x] Hercules
  - [x] WCOSS2

Optional test.

- [x] Run full set of chgres_cube consistency tests on Ursa.

Describe any additional tests performed.

## DEPENDENCIES:
* None

## DOCUMENTATION:
* No updates

## ISSUE: 
* Fixes https://github.com/ufs-community/UFS_UTILS/issues/1087

### CODE REVIEW

File: util/gdas_init/set_fixed_files.sh [hunk 1]
```diff
@@ -38,7 +38,7 @@ ORO_NAME="${CTAR}.mx${OCNRES}_oro_data"
 #---------------------------------------------------------------------------
 
 if [ "$machine" = 'ursa' ] ; then
```
Comment (GeorgeGayno-NOAA) [inline util/gdas_init/set_fixed_files.sh]: Why are you changing the input 'orog' file directory?

File: util/gdas_init/set_fixed_files.sh [hunk 2]
```diff
@@ -38,7 +38,7 @@ ORO_NAME="${CTAR}.mx${OCNRES}_oro_data"
...
-  FIX_ORO_INPUT=/scratch3/NCEPDEV/global/role.glopara/fix/orog/20230615
+  FIX_ORO_INPUT=/scratch3/NCEPDEV/global/role.glopara/fix/orog/20240917
 elif [ "$machine" = 'wcoss2' ] ; then
   FIX_ORO_INPUT=/lfs/h2/emc/global/noscrub/emc.global/FIX/fix/orog/20230615
```
Comment (BrianCurtis-NOAA) [inline util/gdas_init/set_fixed_files.sh]: Did we want to update the date on WCOSS2 as well?

Comment (sanatcumar) [reply util/gdas_init/set_fixed_files.sh]: yes I will do it shortly

Comment (CatherineThomas-NOAA) [reply util/gdas_init/set_fixed_files.sh]: Adding onto this, I think all supported machines should be updated.  I'm not very familiar with jet, but gaea c6 is becoming more widely used for global applications.

Comment (sanatcumar) [reply util/gdas_init/set_fixed_files.sh]: I have updated all the links .

I have access to Orion, Ursa and WCOSS2.  Yet to test on Orion

I do not have access to Gaea, and Jet will need some one to test.

Comment (GeorgeGayno-NOAA) [reply util/gdas_init/set_fixed_files.sh]: Why are you changing FIX_ORO_INPUT?

**Comment by GeorgeGayno-NOAA** [comment]
@sanatcumar - if you can address our comments, we can work to merge this.

**Comment by sanatcumar** [comment]
> @sanatcumar - if you can address our comments, we can work to merge this.
Hi @GeorgeGayno-NOAA  I do not have access to Jet or Gaea and hence could not address this. I have updated the scripts and can i request you to please test. Then we can mark this as resolved ?

**Comment by GeorgeGayno-NOAA** [comment]
@sanatcumar - @BrianCurtis-NOAA and I can test on the machines you can't access.

**Review by GeorgeGayno-NOAA — DISMISSED** [review]
I tried running using v15 data from 2021/03/20/00. The chgres step broke with this error:

` - FATAL ERROR: INCONSISTENT LAND/SEA MASK BETWEEN RESTART AND OROG FILES.`

Your updates to `run_v15.chgres.sh` and `set_fixed_files.sh` will not work because the v15 data was created with different 'orog' files.

File: util/gdas_init/set_fixed_files.sh (hunk 1 above)
Comment (sanatcumar) [reply util/gdas_init/set_fixed_files.sh]: I wanted to test to check if land points are consistent if we pointed to the new orog.   This was a test and I am reverting all of them  now

**Comment by BrianCurtis-NOAA** [comment]
I ran the full suite of reg-tests on Ursa and they passed (manually bumping to latest hash). @sanatcumar would you please update this branch with the latest stuff from ufs-community/develop ?

**Comment by CatherineThomas-NOAA** [comment]
@BrianCurtis-NOAA - I believe that @sanatcumar is no longer with EMC.  Do you know the best way to resolve this?  Do we need to open a new PR or do you have the ability to update the PR without him?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA - I believe that @sanatcumar is no longer with EMC. Do you know the best way to resolve this? Do we need to open a new PR or do you have the ability to update the PR without him?

Thanks for letting me know! This I did not know. Let me see if I can resolve the git differences and I'll process this myself.

**Review by BrianCurtis-NOAA — APPROVED** [review]
